# Lote 2 : Annexe A - Specification technique (02-annexe-a-specification-technique)
import duckdb
D = '02-annexe-a-specification-technique'
R = [
("OBL-0060","TITULAIRE","Concevoir l'architecture navire integree (plateforme, energie, navigation, reseaux, communications, informatique de mission, interfaces AC, diagnostic)","autre","Date d'Effet (DE)","Continu (phase d'ingenierie)","Architecture navire integree","§A1","HAUTE","EXTRAITE",None),
("OBL-0061","TITULAIRE","Transmettre la matrice de tracabilite des exigences (initiale, consolidee, as-built)","livrable","Jalons PDR, CDR, puis chaque acceptation","A la PDR ; a la CDR ; avec chaque dossier d'acceptation","Matrice de tracabilite (CDRL-008)","§A1","HAUTE","EXTRAITE",None),
("OBL-0062","TITULAIRE","Organiser la Revue de Lancement Technique","revue","Date d'Effet (DE)","Dans les 30 jours calendaires suivant la DE","Revue de Lancement Technique","§A2","HAUTE","EXTRAITE","Le jalon KO de l'Annexe D (2026-10-20) est vraisemblablement cette revue (AMBIG-004)"),
("OBL-0063","TITULAIRE","Transmettre le dossier de la Revue de Lancement (organisation d'ingenierie, strategie de gestion des exigences, strategie de gestion des interfaces, proposition de referentiel de criticite cyber, liste initiale des hypotheses de conception)","livrable","Revue de Lancement Technique","Au moins 10 JO avant la revue","Dossier de revue de lancement","§A2","HAUTE","EXTRAITE",None),
("OBL-0064","AC","Confirmer ou commenter le referentiel de criticite cyber","revue","Fin de la Revue de Lancement Technique","10 JO apres la revue","Confirmation / commentaires referentiel cyber","§A2","HAUTE","EXTRAITE",None),
("OBL-0065","TITULAIRE","Maintenir la base des exigences contractuelles et derivees","livrable","Toute la duree de l'ingenierie","Continu","Base d'exigences maintenue","§A3","HAUTE","EXTRAITE",None),
("OBL-0066","TITULAIRE","Soumettre a l'AC toute exigence derivee susceptible d'imposer une contrainte nouvelle a une fourniture de l'AC","changement","Identification d'une telle exigence derivee","Avant son incorporation a la baseline","Soumission d'exigence derivee","§A3","HAUTE","EXTRAITE",None),
("OBL-0067","TITULAIRE","Fournir un export lisible de la base d'exigences","livrable","Chaque SRR, PDR, CDR","A chaque SRR, PDR, CDR","Export de la base d'exigences","§A3","HAUTE","EXTRAITE",None),
("OBL-0068","TITULAIRE","Tenir un registre des interfaces","configuration","Continu","Continu","Registre des interfaces","§A4","HAUTE","EXTRAITE",None),
("OBL-0069","TITULAIRE","Transmettre les Interface Control Documents (ICD) de niveau systeme (preliminaire, approuvable, as-built)","livrable","Jalons PDR, CDR, puis chaque acceptation","A la PDR ; a la CDR ; avec chaque dossier d'acceptation","ICD systeme (CDRL-009)","§A4","HAUTE","EXTRAITE",None),
("OBL-0070","AC","Fournir les donnees d'interface des equipements GFE listes a l'Annexe C","fourniture-ac","Jalons definis a l'Annexe D","Au plus tard aux jalons indiques a l'Annexe D","Donnees d'interface GFE","§A4","HAUTE","EXTRAITE","Detail par element : feuille GFE-GFI de l'Annexe C"),
("OBL-0071","TITULAIRE","Identifier et soumettre a l'AC les hypotheses temporaires utilisees lorsque des donnees GFE sont incompletes","livrable","Formalisation des hypotheses temporaires","5 JO apres leur formalisation","Hypotheses temporaires","§A4","HAUTE","EXTRAITE",None),
("OBL-0072","TITULAIRE","Transmettre le bilan masse et centre de gravite","livrable","De M6 a la CDR : mensuel ; de la CDR a l'acceptation de FNG-02 : trimestriel","Mensuel (M6 -> CDR) ; trimestriel (CDR -> acceptation FNG-02), avec le rapport d'avancement","Bilan masse et centrage (CDRL-010)","§A5","HAUTE","EXTRAITE",None),
("OBL-0073","TITULAIRE","Signaler toute consommation superieure a 50 % de la marge de masse allouee a un sous-ensemble critique, avec une action de maitrise identifiee","risque","Consommation > 50 % de la marge d'un sous-ensemble critique","Dans le rapport suivant","Signalement + action de maitrise","§A5","HAUTE","EXTRAITE",None),
("OBL-0074","TITULAIRE","Transmettre le bilan de puissance electrique (preliminaire, consolide, mis a jour, as-built)","livrable","PDR, CDR, avant la premiere mise sous tension integree de chaque batiment, chaque acceptation","A la PDR ; a la CDR ; avant la 1re mise sous tension integree ; avec chaque dossier d'acceptation","Bilan puissance electrique (CDRL-011)","§A6","HAUTE","EXTRAITE",None),
("OBL-0075","TITULAIRE","Maintenir la liste de configuration logicielle des elements dont il a la responsabilite","configuration","Continu","Continu","Liste de configuration logicielle","§A7","HAUTE","EXTRAITE",None),
("OBL-0076","TITULAIRE","Fournir la declaration de version logicielle (identifiant, fonctions modifiees, anomalies connues, statut des tests de non-regression, dependances de configuration)","livrable","Chaque campagne d'essais a la mer (version candidate)","Au moins 15 jours calendaires avant le debut de la campagne","Declaration de version logicielle","§A7","HAUTE","EXTRAITE",None),
("OBL-0077","TITULAIRE","Notifier toute modification de version apres declaration","configuration","Toute modification de version apres declaration","Avant l'embarquement de la version modifiee dans la configuration d'essai","Notification de modification","§A7","HAUTE","EXTRAITE",None),
("OBL-0078","TITULAIRE","Realiser l'analyse de risques cyber initiale et ses mises a jour","cybersecurite","Avant la PDR, avant la CDR, avant la premiere campagne d'essais a la mer de chaque batiment, avant chaque acceptation","Avant la PDR ; avant la CDR ; avant chaque 1re campagne mer ; avant chaque acceptation","Analyse de risques cyber (CDRL-012)","§A8","HAUTE","EXTRAITE",None),
("OBL-0079","TITULAIRE","Inscrire dans un registre (responsable, traitement prevu, date cible) tout ecart cyber ouvert au moment d'une revue","cybersecurite","Chaque revue avec ecarts cyber ouverts","Au moment de chaque revue","Registre des ecarts cyber","§A8","HAUTE","EXTRAITE",None),
("OBL-0080","TITULAIRE","Ne laisser aucun ecart cyber critique ouvert a l'acceptation sans derogation ecrite de l'AC","cybersecurite","Acceptation de chaque batiment","A chaque acceptation","Ecarts critiques traites ou derogation","§A8","HAUTE","EXTRAITE",None),
("OBL-0081","TITULAIRE","Preparer et transmettre le dossier de readiness de chaque sequence majeure d'essais a quai (configuration, prerequis, procedures, moyens, anomalies ouvertes, analyse de securite, criteres de demarrage)","livrable","Chaque revue de preparation d'essais a quai","15 JO avant la revue correspondante","Dossier de readiness (CDRL-013)","§A9","HAUTE","EXTRAITE",None),
("OBL-0082","AC","Communiquer ses observations sur le dossier de readiness transmis dans les delais","essai","Reception du dossier de readiness dans les delais","Au plus tard 5 JO avant la revue","Observations AC","§A9","HAUTE","EXTRAITE",None),
("OBL-0083","TITULAIRE","Fournir une configuration de reference gelee pour chaque campagne d'essais a la mer","essai","Chaque campagne d'essais a la mer","Au plus tard 10 jours calendaires avant le depart prevu","Configuration de reference (CDRL-015)","§A10","HAUTE","EXTRAITE",None),
("OBL-0084","TITULAIRE","Consigner les ecarts a la configuration gelee dans le journal de configuration de campagne","essai","Tout ecart a la configuration gelee","Pendant la campagne","Journal de configuration de campagne","§A10","HAUTE","EXTRAITE",None),
("OBL-0085","TITULAIRE","Fournir a l'AC un acces aux donnees d'essais contractuellement requises","essai","Acquisition des donnees d'essai","Au plus tard 2 JO apres leur acquisition (sauf delai justifie par un traitement technique)","Acces aux donnees d'essai","§A10","HAUTE","EXTRAITE",None),
("OBL-0086","TITULAIRE","Produire la documentation de soutien de chaque batiment (arborescence logistique, nomenclature de soutien, plans de maintenance, catalogue illustre, documentation de diagnostic, liste des rechanges initiaux)","documentation","Chaque batiment","Selon §A11","Documentation de soutien","§A11","HAUTE","EXTRAITE",None),
("OBL-0087","TITULAIRE","Transmettre la version preliminaire du jeu documentaire de soutien de FNG-01","livrable","Acceptation prevue de FNG-01","6 mois avant l'acceptation prevue de FNG-01","Documentation soutien preliminaire FNG-01 (CDRL-020)","§A11","HAUTE","EXTRAITE",None),
("OBL-0088","TITULAIRE","Transmettre la version preliminaire du jeu documentaire de soutien de FNG-02, integrant le retour d'experience valide de FNG-01","livrable","Acceptation prevue de FNG-02","4 mois avant l'acceptation prevue de FNG-02","Documentation soutien preliminaire FNG-02 (CDRL-021)","§A11","HAUTE","EXTRAITE",None),
("OBL-0089","TITULAIRE","Maintenir un point de contact technique pendant les jours ouvrables durant la periode de soutien initial","soutien","Acceptation de chaque batiment","12 mois suivant l'acceptation","Point de contact technique","§A12","HAUTE","EXTRAITE",None),
("OBL-0090","TITULAIRE","Enregistrer les demandes de soutien et acuser reception de chaque demande","soutien","Chaque demande de soutien","Accuse de reception sous 1 JO","Enregistrement + accuse de reception","§A12","HAUTE","EXTRAITE",None),
("OBL-0091","TITULAIRE","Fournir un premier diagnostic ou une demande d'information complementaire","soutien","Chaque demande de soutien","3 JO","Premier diagnostic / demande d'info","§A12","HAUTE","EXTRAITE",None),
("OBL-0092","TITULAIRE","Transmettre le rapport mensuel de soutien","livrable","Chaque mois de la periode de soutien initial","Au plus tard le 5e JO du mois suivant","Rapport mensuel de soutien (CDRL-028)","§A12","HAUTE","EXTRAITE",None),
("OBL-0093","TITULAIRE","Preparer les trois cursus de formation (equipage, maintenance, administrateur des systemes numeriques)","formation","Date d'Effet (DE)","Avant les premieres sessions","Cursus de formation","§A13","HAUTE","EXTRAITE",None),
("OBL-0094","TITULAIRE","Soumettre les supports de formation en version projet","livrable","Chaque premiere session correspondante","60 jours calendaires avant la premiere session","Supports de formation projet (CDRL-024)","§A13","HAUTE","EXTRAITE",None),
("OBL-0095","AC","Transmettre ses observations sur les supports de formation projet","formation","Reception des supports projet","20 jours calendaires apres reception","Observations AC","§A13","HAUTE","EXTRAITE",None),
("OBL-0096","TITULAIRE","Maintenir un registre unique des anomalies issues des essais sous sa responsabilite","risque","A partir du debut des essais","Continu","Registre unique des anomalies","§A14","HAUTE","EXTRAITE",None),
("OBL-0097","TITULAIRE","Transmettre une synthese des anomalies ouvertes, ventilee par criticite","livrable","Chaque rapport mensuel a partir du debut des essais d'integration a quai","Avec chaque rapport mensuel (a partir du debut des essais a quai)","Synthese des anomalies","§A14","HAUTE","EXTRAITE",None),
("OBL-0098","TITULAIRE","Notifier a l'AC toute anomalie empechant la poursuite d'une sequence d'essais","essai","Classification de l'anomalie","Le jour meme de sa classification","Notification d'anomalie bloquante","§A14","HAUTE","EXTRAITE",None),
("OBL-0099","TITULAIRE","Organiser la revue de retour d'experience de FNG-01","revue","Acceptation de FNG-01","Dans les 45 jours calendaires suivant l'acceptation de FNG-01","Revue RETEX FNG-01","§A15","HAUTE","EXTRAITE",None),
("OBL-0100","TITULAIRE","Transmettre le dossier de revue RETEX","livrable","Revue RETEX FNG-01","10 JO avant la reunion","Dossier RETEX (CDRL-029)","§A15","HAUTE","EXTRAITE",None),
("OBL-0101","TITULAIRE","Transmettre le plan d'integration du retour d'experience sur FNG-02","livrable","Revue RETEX FNG-01","20 JO apres la revue","Plan d'integration RETEX (CDRL-030)","§A15","HAUTE","EXTRAITE",None),
]
con = duckdb.connect('workspace/data/obligations.duckdb')
for r in R:
    con.execute("INSERT OR REPLACE INTO obligations VALUES (?,?,?,?,?,?,?,?,?,?,?,?)",
                (r[0], r[1], r[2], r[3], r[4], r[5], r[6], D, r[7], r[8], r[9], r[10]))
con.execute("INSERT OR REPLACE INTO progress VALUES ('02-annexe-a-specification-technique','EXTRACTED', 'DONE', strftime(now(),'YYYY-MM-DD HH24:MI:SS'))")
print('lote 02 inserte :', len(R), 'obligations')
print('total obligations :', con.execute('select count(*) from obligations').fetchone()[0])
con.close()
